{% set name = "libpeas" %}
{% set version = "1.36.0" %}
{% set version_majmin = '.'.join(version.split('.', 2)[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/{{ name }}/{{ version_majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: 297cb9c2cccd8e8617623d1a3e8415b4530b8e5a893e3527bbfd1edd13237b4c

build:
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
  host:
    - glib
    - gtk3
    - gobject-introspection
    - meson
    - pygobject
    - python
  run:
    - gettext  # [osx]
    - libglib
    - gtk3
    - gobject-introspection
    - pygobject
    - python

test:
  requires:
    - {{ compiler('c') }}
    - pkg-config
    - glib
  commands:
    - test -f ${PREFIX}/include/libpeas-1.0/libpeas/peas.h                   # [unix]
    - test -f ${PREFIX}/lib/libpeas-1.0.dylib                                # [osx]
    - test -f ${PREFIX}/lib/libpeas-1.0.so                                   # [linux]
    - test -f ${PREFIX}/lib/girepository-1.0/Peas-1.0.typelib                # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/libpeas-1.0.pc                         # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/libpeas-gtk-1.0.pc                     # [unix]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\libpeas-1.0.pc exit 1           # [win]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\libpeas-gtk-1.0.pc exit 1       # [win]
    - if not exist %LIBRARY_LIB%\\girepository-1.0\\Peas-1.0.typelib exit 1  # [win]
    - if not exist %LIBRARY_INC%\\libpeas-1.0\\libpeas\\peas.h exit 1        # [win]
    - if not exist %LIBRARY_BIN%\\peas-1.0-1.dll exit 1                      # [win]
    - if not exist %LIBRARY_LIB%\\peas-1.0.lib exit 1                        # [win]

about:
  home: https://gitlab.gnome.org/GNOME/libpeas
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: GObject plugin library

extra:
  recipe-maintainers:
    - tschoonj
